# admin/config.yml
backend:
  name: test-repo
  local_backend: true

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "artworks"
    label: "Artworks"
    files:
      - file: "data/artworks.json"
        label: "Artwork List"
        name: "artwork_list"
        format: "json"
        fields:
          - label: "Artworks"
            name: "artworks"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Medium", name: "medium", widget: "string" }
              - { label: "Dimensions", name: "dimensions", widget: "string" }
              - { label: "Tags", name: "tags", widget: "list" }
              - { label: "Availability", name: "availability", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }

